# Generated by Django 3.1.6 on 2021-02-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='place_name',
        ),
    ]
